version: '3.8'

services:
  db:
    image: postgres:latest
    env_file: .env
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
        - "5432:5432"
    networks:
      - backend

  bot:
    build: .
    command: python bot.py
    env_file: .env
    restart: always
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
